# Generated by Django 5.2.7 on 2025-11-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrillSession',
        ),
    ]
